package com.unis.service;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 */
@WebServiceClient(name = "SingleServiceImplService", targetNamespace = "http://service.unis.com/", wsdlLocation = "http://localhost:8080/LamsDataIF/cxf/ArcDataWsSingle?wsdl")
public class SingleServiceImplService
        extends Service {

    private final static URL SINGLESERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SINGLESERVICEIMPLSERVICE_EXCEPTION;
    private final static QName SINGLESERVICEIMPLSERVICE_QNAME = new QName("http://service.unis.com/", "SingleServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/LamsDataIF/cxf/ArcDataWsSingle?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SINGLESERVICEIMPLSERVICE_WSDL_LOCATION = url;
        SINGLESERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public SingleServiceImplService() {
        super(__getWsdlLocation(), SINGLESERVICEIMPLSERVICE_QNAME);
    }


    public SingleServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SINGLESERVICEIMPLSERVICE_QNAME);
    }


    public SingleServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * @return returns ArcDataWsSingle
     */
    @WebEndpoint(name = "ArcDataWsSinglePort")
    public ArcDataWsSingle getArcDataWsSinglePort() {
        return super.getPort(new QName("http://service.unis.com/", "ArcDataWsSinglePort"), ArcDataWsSingle.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns ArcDataWsSingle
     */
    @WebEndpoint(name = "ArcDataWsSinglePort")
    public ArcDataWsSingle getArcDataWsSinglePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.unis.com/", "ArcDataWsSinglePort"), ArcDataWsSingle.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SINGLESERVICEIMPLSERVICE_EXCEPTION != null) {
            throw SINGLESERVICEIMPLSERVICE_EXCEPTION;
        }
        return SINGLESERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
